# 🐼 Pandas - Class 7: Merging, Joining & Concatenation
Welcome to **Class 7** of our Pandas series. Today we’ll learn how to combine multiple DataFrames using different techniques.

## 1. Using `concat()` for Stacking Data
- `pd.concat()` combines DataFrames vertically (rows) or horizontally (columns).
- Use `axis=0` for vertical stacking (default), `axis=1` for horizontal.
- `ignore_index=True` can reset the index after concatenation.

In [16]:

# Dataset 1: Product details
import pandas as pd

data1 = {
    "Product": ["Laptop", "Mobile", "Headphones", "Keyboard", "Mouse"],
    "Price": [55000, 25000, 2000, 1500, 800],
    "Stock": [10, 25, 50, 30, 45]
}

df1 = pd.DataFrame(data1)

print(df1)

# Dataset 2: More products (same columns as df1 → good for vertical stacking)
data2 = {
    "Product": ["Monitor", "Printer", "Tablet", "Webcam", "Speaker"],
    "Price": [12000, 8000, 18000, 2500, 3000],
    "Stock": [15, 20, 12, 35, 40]
}

df2 = pd.DataFrame(data2)

print(df2)

# Dataset 3: Additional info (different columns → good for horizontal stacking)
data3 = {
    "Rating": [4.5, 4.3, 4.2, 4.4, 4.1],
    "Category": ["Electronics", "Electronics", "Accessories", "Accessories", "Accessories"]
}

df3 = pd.DataFrame(data3)

print(df3)

      Product  Price  Stock
0      Laptop  55000     10
1      Mobile  25000     25
2  Headphones   2000     50
3    Keyboard   1500     30
4       Mouse    800     45
   Product  Price  Stock
0  Monitor  12000     15
1  Printer   8000     20
2   Tablet  18000     12
3   Webcam   2500     35
4  Speaker   3000     40
   Rating     Category
0     4.5  Electronics
1     4.3  Electronics
2     4.2  Accessories
3     4.4  Accessories
4     4.1  Accessories

In [17]:
pd.concat([df1,df2],ignore_index=True)

      Product  Price  Stock
0      Laptop  55000     10
1      Mobile  25000     25
2  Headphones   2000     50
3    Keyboard   1500     30
4       Mouse    800     45
5     Monitor  12000     15
6     Printer   8000     20
7      Tablet  18000     12
8      Webcam   2500     35
9     Speaker   3000     40

In [18]:
pd.concat([df1,df2],axis=1)

      Product  Price  Stock  Product  Price  Stock
0      Laptop  55000     10  Monitor  12000     15
1      Mobile  25000     25  Printer   8000     20
2  Headphones   2000     50   Tablet  18000     12
3    Keyboard   1500     30   Webcam   2500     35
4       Mouse    800     45  Speaker   3000     40

In [19]:
pd.concat([df1,df3],axis=1)

      Product  Price  Stock  Rating     Category
0      Laptop  55000     10     4.5  Electronics
1      Mobile  25000     25     4.3  Electronics
2  Headphones   2000     50     4.2  Accessories
3    Keyboard   1500     30     4.4  Accessories
4       Mouse    800     45     4.1  Accessories

## 2. Using `merge()` for SQL-Style Joins
- `merge()` is similar to SQL joins.
- Specify `on` or `left_on`/`right_on` to choose key columns.
- Join types: `inner` (default), `left`, `right`, `outer`.

In [30]:
import pandas as pd

# Product data
products = {
    "Product": ["Laptop", "Mobile", "Headphones", "Keyboard", "Mouse"],
    "Price": [55000, 25000, 2000, 1500, 800],
    "Stock": [10, 25, 50, 30, 45]
}

# Dictionary → DataFrame
products = pd.DataFrame(products)

# Sales DataFrame
sales_data = {
    "Order_ID": [101, 102, 103, 104, 105],
    "Product": ["Laptop", "Mobile", "Laptop", "Headphones", "Mouse"],
    "Sales": [55000, 25000, 60000, 4000, 1200],
    "Quantity": [1, 2, 1, 2, 2]
}

df = pd.DataFrame(sales_data)

   Order_ID  Quantity
0       101         1
1       102         2
2       103         1
3       104         2
4       105         2
5       106         3
6       107         1
7       108         2

In [31]:
pd.merge(products,df)

      Product  Price  Stock  Order_ID  Sales  Quantity
0      Laptop  55000     10       101  55000         1
1      Laptop  55000     10       103  60000         1
2      Mobile  25000     25       102  25000         2
3  Headphones   2000     50       104   4000         2
4       Mouse    800     45       105   1200         2

In [35]:
pd.merge(products, df, on="Product", how="left")

      Product  Price  Stock  Order_ID    Sales  Quantity
0      Laptop  55000     10     101.0  55000.0       1.0
1      Laptop  55000     10     103.0  60000.0       1.0
2      Mobile  25000     25     102.0  25000.0       2.0
3  Headphones   2000     50     104.0   4000.0       2.0
4    Keyboard   1500     30       NaN      NaN       NaN
5       Mouse    800     45     105.0   1200.0       2.0

In [37]:
pd.merge(products, df, on="Product", how="right")

      Product  Price  Stock  Order_ID  Sales  Quantity
0      Laptop  55000     10       101  55000         1
1      Mobile  25000     25       102  25000         2
2      Laptop  55000     10       103  60000         1
3  Headphones   2000     50       104   4000         2
4       Mouse    800     45       105   1200         2

In [38]:
pd.merge(products, df, on="Product", how="outer")

      Product  Price  Stock  Order_ID    Sales  Quantity
0  Headphones   2000     50     104.0   4000.0       2.0
1    Keyboard   1500     30       NaN      NaN       NaN
2      Laptop  55000     10     101.0  55000.0       1.0
3      Laptop  55000     10     103.0  60000.0       1.0
4      Mobile  25000     25     102.0  25000.0       2.0
5       Mouse    800     45     105.0   1200.0       2.0

In [39]:
pd.merge(products, df, on="Product", how="inner")

      Product  Price  Stock  Order_ID  Sales  Quantity
0      Laptop  55000     10       101  55000         1
1      Laptop  55000     10       103  60000         1
2      Mobile  25000     25       102  25000         2
3  Headphones   2000     50       104   4000         2
4       Mouse    800     45       105   1200         2

## 3. Using `join()` with Index Alignment
- `join()` joins DataFrames on their index or on a key column.
- By default, joins on index; can specify `on='col'`.
- Useful for adding columns to an existing DataFrame.

## 4. Practical Examples
- Combine sales and revenue data to see performance.
- Merge students with marks to link records.
- Practice with realistic datasets to understand alignment and missing data handling.

In [43]:
import pandas as pd

sales = pd.DataFrame({
    "Product": ["Laptop", "Mobile", "Headphones", "Mouse"],
    "Units_Sold": [10, 20, 30, 40]
})

revenue = pd.DataFrame({
    "Product": ["Laptop", "Mobile", "Headphones", "Mouse"],
    "Revenue": [550000, 500000, 120000, 32000]
})

performance = pd.merge(sales, revenue, on="Product",how = "outer")

print(performance)

      Product  Units_Sold  Revenue
0  Headphones          30   120000
1      Laptop          10   550000
2      Mobile          20   500000
3       Mouse          40    32000

## Mini Practice
1. Create three DataFrames: Products, Sales, and Revenue.
2. Concatenate them vertically and horizontally.
3. Merge Sales and Revenue using different join types.
4. Join Products with Sales based on index or a key.
5. Analyze missing values after joins.

In [ ]:

# 1. Create three DataFrames: Products, Sales, and Revenue
import pandas as pd

products = pd.DataFrame({
    "Product": ["Laptop", "Mobile", "Headphones", "Keyboard", "Mouse"],
    "Price": [55000, 25000, 2000, 1500, 800],
    "Stock": [10, 25, 50, 30, 45]
})

print(products)

sales = pd.DataFrame({
    "Product": ["Laptop", "Mobile", "Headphones", "Keyboard", "Mouse"],
    "Units_Sold": [8, 20, 35, 15, 30],
    "City": ["Mumbai", "Pune", "Delhi", "Mumbai", "Nashik"]
})

print(sales)

revenue = pd.DataFrame({
    "Product": ["Laptop", "Mobile", "Headphones", "Keyboard", "Mouse"],
    "Revenue": [440000, 500000, 70000, 22500, 24000],
    "Profit": [80000, 100000, 15000, 5000, 6000]
})

print(revenue)

In [44]:
# 2. Concatenate them vertically and horizontally


pd.concat([products,sales,revenue],axis = 0)

      Product    Price  Stock  Units_Sold   Revenue
0      Laptop  55000.0   10.0         NaN       NaN
1      Mobile  25000.0   25.0         NaN       NaN
2  Headphones   2000.0   50.0         NaN       NaN
3    Keyboard   1500.0   30.0         NaN       NaN
4       Mouse    800.0   45.0         NaN       NaN
5     Monitor  12000.0   15.0         NaN       NaN
6     Printer   8000.0   20.0         NaN       NaN
7      Tablet  18000.0   12.0         NaN       NaN
8      Webcam   2500.0   35.0         NaN       NaN
9     Speaker   3000.0   40.0         NaN       NaN
0      Laptop      NaN    NaN        10.0       NaN
1      Mobile      NaN    NaN        20.0       NaN
2  Headphones      NaN    NaN        30.0       NaN
3       Mouse      NaN    NaN        40.0       NaN
0      Laptop      NaN    NaN         NaN  550000.0
1      Mobile      NaN    NaN         NaN  500000.0
2  Headphones      NaN    NaN         NaN  120000.0
3       Mouse      NaN    NaN         NaN   32000.0

In [45]:
pd.concat([products,sales,revenue],axis = 1)

      Product  Price  Stock     Product  Units_Sold     Product   Revenue
0      Laptop  55000     10      Laptop        10.0      Laptop  550000.0
1      Mobile  25000     25      Mobile        20.0      Mobile  500000.0
2  Headphones   2000     50  Headphones        30.0  Headphones  120000.0
3    Keyboard   1500     30       Mouse        40.0       Mouse   32000.0
4       Mouse    800     45         NaN         NaN         NaN       NaN
5     Monitor  12000     15         NaN         NaN         NaN       NaN
6     Printer   8000     20         NaN         NaN         NaN       NaN
7      Tablet  18000     12         NaN         NaN         NaN       NaN
8      Webcam   2500     35         NaN         NaN         NaN       NaN
9     Speaker   3000     40         NaN         NaN         NaN       NaN

In [47]:
# 3. Merge Sales and Revenue using different join types (inner, left, right, outer)

pd.merge(sales,revenue,on ="Product",how = "left" )

      Product  Units_Sold  Revenue
0      Laptop          10   550000
1      Mobile          20   500000
2  Headphones          30   120000
3       Mouse          40    32000

In [48]:
# 3. Merge Sales and Revenue using different join types (inner, left, right, outer)

pd.merge(sales,revenue,on ="Product",how = "right" )

      Product  Units_Sold  Revenue
0      Laptop          10   550000
1      Mobile          20   500000
2  Headphones          30   120000
3       Mouse          40    32000

In [51]:
# 4. Join Products with Sales based on index or a key


result = products.join(
    sales.set_index("Product"),
    on="Product"
)

print(result)

      Product  Price  Stock  Units_Sold
0      Laptop  55000     10        10.0
1      Mobile  25000     25        20.0
2  Headphones   2000     50        30.0
3    Keyboard   1500     30         NaN
4       Mouse    800     45        40.0
5     Monitor  12000     15         NaN
6     Printer   8000     20         NaN
7      Tablet  18000     12         NaN
8      Webcam   2500     35         NaN
9     Speaker   3000     40         NaN

In [52]:
# 5. Analyze missing values after joins
# Use isna(), info(), or describe() to explore gaps


result.describe()

              Price      Stock  Units_Sold
count     10.000000  10.000000    4.000000
mean   12780.000000  28.200000   25.000000
std    16901.203113  14.109099   12.909944
min      800.000000  10.000000   10.000000
25%     2125.000000  16.250000   17.500000
50%     5500.000000  27.500000   25.000000
75%    16500.000000  38.750000   32.500000
max    55000.000000  50.000000   40.000000

---
## Summary
- Used `concat()` for stacking data vertically and horizontally.
- Performed SQL-style joins with `merge()`.
- Applied `join()` with index alignment.
- Explored practical use-cases like sales vs revenue, students vs marks.