# 🐼 Pandas - Class 5: Sorting & Basic Statistics
Welcome to **Class 5** of our Pandas series. Today we’ll learn how to sort data and calculate basic statistics.

## 1. Sorting Data
- Use `sort_values(by='col')` to sort by column values.
- Use `ascending=False` for descending order.
- Sort by multiple columns by passing a list.
- `sort_index()` sorts by row or column index.

In [16]:
import numpy as np
import pandas as pd

data = {
    "Product": ["Laptop", "Mobile", "Headphones", "Keyboard", "Mouse"],
    "Price": [55000, 25000, 2000, 1500, 800],
    "Stock": [10, 25, 50, 30, 45],
    "Rating": [4.5, 4.3, 4.2, 4.4, 4.1]
}

df = pd.DataFrame(data)

print(df)

      Product  Price  Stock  Rating
0      Laptop  55000     10     4.5
1      Mobile  25000     25     4.3
2  Headphones   2000     50     4.2
3    Keyboard   1500     30     4.4
4       Mouse    800     45     4.1

In [17]:
df.sort_values(by = "Price")

      Product  Price  Stock  Rating
4       Mouse    800     45     4.1
3    Keyboard   1500     30     4.4
2  Headphones   2000     50     4.2
1      Mobile  25000     25     4.3
0      Laptop  55000     10     4.5

In [18]:
#Sort by multiple columns by passing a list.
#(Price ascending,Stock descending)
df.sort_values(by = ["Price","Stock"],ascending = [True,False])

      Product  Price  Stock  Rating
4       Mouse    800     45     4.1
3    Keyboard   1500     30     4.4
2  Headphones   2000     50     4.2
1      Mobile  25000     25     4.3
0      Laptop  55000     10     4.5

## 2. Descriptive Statistics
- `mean()`, `median()`, `mode()` for central tendency.
- `std()` for standard deviation.
- `describe()` for a summary of stats (count, mean, std, min, quartiles, max).

In [19]:
df.mean(numeric_only = True)

Price     16860.0
Stock        32.0
Rating        4.3
dtype: float64

In [20]:
df.median(numeric_only = True)

Price     2000.0
Stock       30.0
Rating       4.3
dtype: float64

In [21]:
df.mode(numeric_only = True)

   Price  Stock  Rating
0    800     10     4.1
1   1500     25     4.2
2   2000     30     4.3
3  25000     45     4.4
4  55000     50     4.5

In [22]:
df.std(numeric_only = True)

Price     23641.023666
Stock        16.046807
Rating        0.158114
dtype: float64

In [23]:
df.describe()

              Price      Stock    Rating
count      5.000000   5.000000  5.000000
mean   16860.000000  32.000000  4.300000
std    23641.023666  16.046807  0.158114
min      800.000000  10.000000  4.100000
25%     1500.000000  25.000000  4.200000
50%     2000.000000  30.000000  4.300000
75%    25000.000000  45.000000  4.400000
max    55000.000000  50.000000  4.500000

## 3. Counting Values
- `value_counts()` shows the frequency of unique values in a Series.
- Use `normalize=True` to see percentages instead of counts.

In [24]:
df["Product"].value_counts()

Product
Laptop        1
Mobile        1
Headphones    1
Keyboard      1
Mouse         1
Name: count, dtype: int64

In [27]:
df["Product"].value_counts(normalize = True)

Product
Laptop        0.2
Mobile        0.2
Headphones    0.2
Keyboard      0.2
Mouse         0.2
Name: proportion, dtype: float64

## 4. Correlation & Covariance
- `corr()` computes correlation between numeric columns.
- `cov()` computes covariance.
- Correlation values range from -1 (negative) to +1 (positive).

In [28]:
df.corr(numeric_only=True)

           Price     Stock    Rating
Price   1.000000 -0.884114  0.721648
Stock  -0.884114  1.000000 -0.886796
Rating  0.721648 -0.886796  1.000000

In [29]:
df.cov(numeric_only=True)

              Price      Stock    Rating
Price   558898000.0 -335400.00  2697.500
Stock     -335400.0     257.50    -2.250
Rating       2697.5      -2.25     0.025

In [30]:
df["Price"].corr(df["Stock"])

np.float64(-0.8841137885327218)

## Mini Practice
1. Build a DataFrame with columns: Name, Age, Score, Height.
2. Sort the data by Score (descending).
3. Get mean, median, mode, and std of numeric columns.
4. Use value_counts on Name or any categorical column.
5. Compute corr() and cov() for all numeric columns.

In [31]:
# Write your mini practice solution here

# 1. Build a DataFrame with columns: Name, Age, Score, Height
import pandas as pd

data = {
    "Name": ["Vaishnavi", "Rahul", "Priya", "Aman", "Sneha"],
    "Age": [21, 22, 20, 23, 21],
    "Score": [85, 90, 78, 92, 88],
    "Height": [165, 172, 160, 175, 168]
}

df = pd.DataFrame(data)

print(df)

        Name  Age  Score  Height
0  Vaishnavi   21     85     165
1      Rahul   22     90     172
2      Priya   20     78     160
3       Aman   23     92     175
4      Sneha   21     88     168

In [32]:
# 2. Sort the data by Score (descending)
df.sort_values(by = "Score",ascending = False)

        Name  Age  Score  Height
3       Aman   23     92     175
1      Rahul   22     90     172
4      Sneha   21     88     168
0  Vaishnavi   21     85     165
2      Priya   20     78     160

In [33]:
# 3. Get mean, median, mode, and std of numeric columns
df.mean(numeric_only=True)

Age        21.4
Score      86.6
Height    168.0
dtype: float64

In [34]:
df.median(numeric_only=True)

Age        21.0
Score      88.0
Height    168.0
dtype: float64

In [35]:
df.mode(numeric_only=True)

    Age  Score  Height
0  21.0     78     160
1   NaN     85     165
2   NaN     88     168
3   NaN     90     172
4   NaN     92     175

In [36]:
df.std(numeric_only=True)

Age       1.140175
Score     5.458938
Height    5.873670
dtype: float64

In [38]:
 #4. Use value_counts on Name or any categorical column
df["Name"].value_counts()

Name
Vaishnavi    1
Rahul        1
Priya        1
Aman         1
Sneha        1
Name: count, dtype: int64

In [39]:

# 5. Compute corr() and cov() for all numeric columns
df.corr(numeric_only=True)

             Age     Score    Height
Age     1.000000  0.915788  0.970582
Score   0.915788  1.000000  0.974613
Height  0.970582  0.974613  1.000000

In [40]:
df.cov(numeric_only=True)

        Age  Score  Height
Age     1.3   5.70    6.50
Score   5.7  29.80   31.25
Height  6.5  31.25   34.50

---
## Summary
- Learned to sort by columns with `sort_values` and by index with `sort_index`.
- Explored descriptive statistics: mean, median, mode, std, describe.
- Counted values with `value_counts`.
- Calculated correlation and covariance.