# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [6]:
import numpy as np

import pandas as pd

data = {
    "Name": ["Vaishnavi", "Rahul", "Priya", "Aman", "Sneha"],
    "Age": [21, 22, 20, 23, 21],
    "Score": [85, 78, 92, 74, 88]
}

df = pd.DataFrame(data)

print(df)

        Name  Age  Score
0  Vaishnavi   21     85
1      Rahul   22     78
2      Priya   20     92
3       Aman   23     74
4      Sneha   21     88

In [7]:
df[df["Age"]>20]

        Name  Age  Score
0  Vaishnavi   21     85
1      Rahul   22     78
3       Aman   23     74
4      Sneha   21     88

In [8]:
df[(df["Age"]>20) & (df["Score"]>70)]

        Name  Age  Score
0  Vaishnavi   21     85
1      Rahul   22     78
3       Aman   23     74
4      Sneha   21     88

In [13]:
df[(df["Age"]>22) | (df["Score"]>80)]

        Name  Age  Score
0  Vaishnavi   21     85
2      Priya   20     92
3       Aman   23     74
4      Sneha   21     88

In [14]:
df[~(df["Score"]>80)]

    Name  Age  Score
1  Rahul   22     78
3   Aman   23     74

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

In [15]:
df[(df["Age"]>20) & (df["Score"]>70)]

        Name  Age  Score
0  Vaishnavi   21     85
1      Rahul   22     78
3       Aman   23     74
4      Sneha   21     88

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [16]:
#Simple query : Age >25

df.query("Age < 22")

        Name  Age  Score
0  Vaishnavi   21     85
2      Priya   20     92
4      Sneha   21     88

In [18]:
#Multiple Conditions : Age < 35 and Score >= 85

df.query("Age < 35 and Score >= 85")

        Name  Age  Score
0  Vaishnavi   21     85
2      Priya   20     92
4      Sneha   21     88

In [20]:
#Creating a variable inside the query

hold = 88
df.query("Score > @hold")

    Name  Age  Score
2  Priya   20     92

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [21]:
df

        Name  Age  Score
0  Vaishnavi   21     85
1      Rahul   22     78
2      Priya   20     92
3       Aman   23     74
4      Sneha   21     88

In [22]:
df["Name"].str.lower()

0    vaishnavi
1        rahul
2        priya
3         aman
4        sneha
Name: Name, dtype: object

In [24]:
df["Name"].str.contains("p",case = False)

0    False
1    False
2     True
3    False
4    False
Name: Name, dtype: bool

In [27]:
df["Name"].str.replace("Rahul","Niketan")

0    Vaishnavi
1      Niketan
2        Priya
3         Aman
4        Sneha
Name: Name, dtype: object

In [28]:
df["Name"].str.startswith("A")

0    False
1    False
2    False
3     True
4    False
Name: Name, dtype: bool

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [30]:


# 1. Build a DataFrame with columns: Name, Age, City, Score
import numpy as np

import pandas as pd

data = {
    "Name": ["Vaishnavi", "Rahul", "Priya", "Aman", "Sneha"],
    "Age": [21, 22, 20, 23, 21],
    "City": ["Mumbai", "Pune", "Nashik", "Thane", "Nagpur"],
    "Score": [85, 90, 78, 92, 88]
}

df = pd.DataFrame(data)
df

# 2. Use boolean indexing to select rows where Age > 25
# Write your code here

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here

        Name  Age    City  Score
0  Vaishnavi   21  Mumbai     85
1      Rahul   22    Pune     90
2      Priya   20  Nashik     78
3       Aman   23   Thane     92
4      Sneha   21  Nagpur     88

In [31]:
# 2. Use boolean indexing to select rows where Age > 25
df["Age"]>25

0    False
1    False
2    False
3    False
4    False
Name: Age, dtype: bool

In [34]:
# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
df[(df["City"] == "Delhi") | (df["City"] == "Mumbai")]

        Name  Age    City  Score
0  Vaishnavi   21  Mumbai     85

In [35]:
#Use query() to find rows with Score >= 85 and Age < 35

df.query("Score >= 85 and Age < 35")

        Name  Age    City  Score
0  Vaishnavi   21  Mumbai     85
1      Rahul   22    Pune     90
3       Aman   23   Thane     92
4      Sneha   21  Nagpur     88

In [39]:
#5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"



df["City"].replace("Pune", "Navi Mumbai").str.lower()

0         mumbai
1    navi mumbai
2         nashik
3          thane
4         nagpur
Name: City, dtype: object

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.