# 🐼 Pandas - Class 6: GroupBy & Aggregations
Welcome to **Class 6** of our Pandas series. Today we’ll learn how to group data and perform aggregations.

## 1. Concept of Split–Apply–Combine
- **Split** the data into groups based on some criteria.
- **Apply** a function (e.g., sum, mean) to each group.
- **Combine** the results into a new DataFrame or Series.

This is the core idea behind `groupby`.

In [ ]:
import pandas as pd

# New dataset: Employees, their Department, and Salary
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
  Employee Department  Salary
0     John         HR   50000
1    Sarah         IT   70000
2     Mike         IT   72000
3     Anna    Finance   65000
4      Tom    Finance   60000
5    Laura         HR   52000
6    Steve         IT   75000
7     Kate    Finance   58000

In [ ]:
#To see departments uniquely

df["Department"].value_counts()

Department
IT         3
Finance    3
HR         2
Name: count, dtype: int64

In [ ]:
#Average Salary of the "IT" department

df[df["Department"] == "IT"]["Salary"].mean()

np.float64(72333.33333333333)

In [ ]:
#Every department's average salary

df.groupby("Department")["Salary"].mean()

Department
Finance    61000.000000
HR         51000.000000
IT         72333.333333
Name: Salary, dtype: float64

In [ ]:
#Employee Count of the Deparment

df.groupby("Department")["Employee"].count()

Department
Finance    3
HR         2
IT         3
Name: Employee, dtype: int64

In [ ]:
df.groupby("Department")["Salary"].agg(["mean","min","max"])

                    mean    min    max
Department
Finance     61000.000000  58000  65000
HR          51000.000000  50000  52000
IT          72333.333333  70000  75000

## 2. Using `groupby()` with Aggregation Functions
- Use `groupby('col').mean()` or other functions like sum, count, min, max.
- You can also use `agg()` to pass multiple functions at once.

In [ ]:
df.groupby("Department")["Salary"].agg(["mean","max"])

                    mean    max
Department
Finance     61000.000000  65000
HR          51000.000000  52000
IT          72333.333333  75000

## 3. Multiple Aggregations on Different Columns
- With `agg()`, you can specify different functions for each column.
- Example: `df.groupby('Dept').agg({'Salary':'mean', 'Age':'max'})`.

In [ ]:
import pandas as pd

# Same dataset
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26

In [ ]:
df.groupby("Department").agg({
    "Salary":["mean","max","min"],
    "Age":["mean","max"]
})

                  Salary                      Age
                    mean    max    min       mean max
Department
Finance     61000.000000  65000  58000  29.333333  35
HR          51000.000000  52000  50000  28.500000  29
IT          72333.333333  75000  70000  31.000000  32

## 4. Pivot Tables & Crosstab
- `pivot_table()` summarizes data like Excel pivot tables.
- `crosstab()` shows frequency counts of combinations of factors.
- Both are powerful for summarizing and comparing groups.

In [ ]:
df["AgeGroup"] = pd.cut(df["Age"], bins=[25, 30, 35, 40], labels=["25-30", "31-35", "36-40"])
crosstab_result = pd.crosstab(df["Department"], df["AgeGroup"])
df

  Employee Department  Salary  Age AgeGroup
0     John         HR   50000   28    25-30
1    Sarah         IT   70000   32    31-35
2     Mike         IT   72000   30    25-30
3     Anna    Finance   65000   27    25-30
4      Tom    Finance   60000   35    31-35
5    Laura         HR   52000   29    25-30
6    Steve         IT   75000   31    31-35
7     Kate    Finance   58000   26    25-30

In [ ]:
df.pivot_table(values = "Salary",index = "Department")

                  Salary
Department
Finance     61000.000000
HR          51000.000000
IT          72333.333333

In [ ]:
df.pivot_table(values = "Salary",index = "Department",aggfunc="mean")

                  Salary
Department
Finance     61000.000000
HR          51000.000000
IT          72333.333333

In [ ]:
#Column ko cut karneke liye "pd.cut()" use karte hai

df["AgeGroup"] = pd.cut(df["Age"],bins = [25,30,35,40],labels = ["25-30","31-35","36-40"])
df

  Employee Department  Salary  Age AgeGroup
0     John         HR   50000   28    25-30
1    Sarah         IT   70000   32    31-35
2     Mike         IT   72000   30    25-30
3     Anna    Finance   65000   27    25-30
4      Tom    Finance   60000   35    31-35
5    Laura         HR   52000   29    25-30
6    Steve         IT   75000   31    31-35
7     Kate    Finance   58000   26    25-30

In [ ]:
pd.crosstab(df["Department"],df["AgeGroup"])

AgeGroup    25-30  31-35
Department
Finance         2      1
HR              2      0
IT              1      2

## Mini Practice
1. Create a DataFrame with columns: Department, Employee, Salary, Age, City.
2. Group by Department to get average Salary and max Age.
3. Apply multiple aggregations using agg().
4. Create a pivot_table to see mean Salary by Department and City.
5. Build a crosstab for Department vs City.

In [ ]:

# 1. Create a DataFrame with columns: Department, Employee, Salary, Age, City
import pandas as pd

data = {
    "Department": ["IT", "HR", "Finance", "IT", "Marketing"],
    "Employee": ["Rahul", "Priya", "Aman", "Sneha", "Rohit"],
    "Salary": [55000, 45000, 60000, 52000, 48000],
    "Age": [25, 28, 30, 24, 27],
    "City": ["Mumbai", "Pune", "Delhi", "Nashik", "Thane"]
}

df = pd.DataFrame(data)

print(df)

  Department Employee  Salary  Age    City
0         IT    Rahul   55000   25  Mumbai
1         HR    Priya   45000   28    Pune
2    Finance     Aman   60000   30   Delhi
3         IT    Sneha   52000   24  Nashik
4  Marketing    Rohit   48000   27   Thane

In [ ]:
# 2. Group by Department to get average Salary and max Age

df.groupby("Department").agg({
    "Salary": "mean",
    "Age": "max"
})

             Salary  Age
Department
Finance     60000.0   30
HR          45000.0   28
IT          53500.0   25
Marketing   48000.0   27

In [ ]:
# 3. Apply multiple aggregations using agg()
# Example: mean Salary, max Age per Department

df.groupby("Department").agg({
    "Salary": "mean",
    "Age": "max"
})

             Salary  Age
Department
Finance     60000.0   30
HR          45000.0   28
IT          53500.0   25
Marketing   48000.0   27

In [ ]:
# 4. Create a pivot_table to see mean Salary by Department and City
# Write your code here

df.pivot_table(values = "Salary",index = ["Department","City"],aggfunc="mean" )

                    Salary
Department City
Finance    Delhi   60000.0
HR         Pune    45000.0
IT         Mumbai  55000.0
           Nashik  52000.0
Marketing  Thane   48000.0

In [ ]:
# 5. Build a crosstab for Department vs City
# Write your code here

pd.crosstab(df["Department"],df['City'])

City        Delhi  Mumbai  Nashik  Pune  Thane
Department
Finance         1       0       0     0      0
HR              0       0       0     1      0
IT              0       1       1     0      0
Marketing       0       0       0     0      1

---
## Summary
- Learned the split–apply–combine concept.
- Used `groupby()` with aggregation functions.
- Applied multiple aggregations to different columns.
- Explored `pivot_table` and `crosstab` for summarizing data.