# 🐼 Pandas - Class 11: Advanced Tricks & Performance
Welcome to **Class 11** of our Pandas series. Today we’ll explore advanced techniques to write efficient, clean, and optimized Pandas code.

## 1. Applying Custom Functions with `apply()` / `map()`
- `apply()` lets you apply a custom function across rows or columns.
- `map()` is for applying functions element-wise to a Series.
- Both are handy for transformations, calculations, and cleaning data.

In [27]:
import pandas as pd

data = {
    "Name": ["Aarav", "Isha", "Rahul", "Sneha", "Kabir"],
    "Maths": [85, 92, 78, 88, 95],
    "Science": [420, 450, 380, 440, 465]
}

df = pd.DataFrame(data)

print(df)

    Name  Maths  Science
0  Aarav     85      420
1   Isha     92      450
2  Rahul     78      380
3  Sneha     88      440
4  Kabir     95      465

In [28]:
df["Total Marks"] = df[["Maths", "Science"]].apply(
    lambda row: row.sum(),
    axis=1
)

print(df)

    Name  Maths  Science  Total Marks
0  Aarav     85      420          505
1   Isha     92      450          542
2  Rahul     78      380          458
3  Sneha     88      440          528
4  Kabir     95      465          560

In [29]:
col_mean = df[["Maths","Science"]].apply(lambda col :col.mean())
col_mean

Maths       87.6
Science    431.0
dtype: float64

In [30]:
def Grade(s):
  if s>=90:
    return "A"
  elif s>=80:
    return "B"
  elif s>=70:
    return "C"
  else:
    return "D"

df["Maths Grades"] = df["Maths"].apply(Grade)
df

    Name  Maths  Science  Total Marks Maths Grades
0  Aarav     85      420          505            B
1   Isha     92      450          542            A
2  Rahul     78      380          458            C
3  Sneha     88      440          528            B
4  Kabir     95      465          560            A

In [32]:
df["Name_l"]=df["Name"].map(str.lower)
df

    Name  Maths  Science  Total Marks Maths Grades Name_l
0  Aarav     85      420          505            B  aarav
1   Isha     92      450          542            A   isha
2  Rahul     78      380          458            C  rahul
3  Sneha     88      440          528            B  sneha
4  Kabir     95      465          560            A  kabir

In [33]:
df["Bonus Maths"] = df["Maths"].map(lambda v:v+5)
df

    Name  Maths  Science  Total Marks Maths Grades Name_l  Bonus Maths
0  Aarav     85      420          505            B  aarav           90
1   Isha     92      450          542            A   isha           97
2  Rahul     78      380          458            C  rahul           83
3  Sneha     88      440          528            B  sneha           93
4  Kabir     95      465          560            A  kabir          100